-- ============================================================
-- WinePass — Phase 2 schema: bookings table + booking_ref RPC
--
-- Run this in the Supabase SQL editor for project
-- bhpcmfghmfvzaxfjsbfp (same project as schema_phase1.sql).
--
-- NOTE: the `bookings` table and `generate_booking_ref()` RPC
-- already exist in this project (created outside this repo's SQL
-- files). The `create table if not exists` below is a no-op there
-- and is kept only so this file is complete if ever run against a
-- fresh database. The `alter table` block at the bottom is the part
-- that actually needs to run against the live project — it adds the
-- three guest-contact columns used by the Phase 2
-- /book/[slug]/details step (guest_name, guest_phone,
-- special_requests), which the existing table is missing.
--
-- booking_ref is the human-facing "confirmation code", already
-- generated by the existing generate_booking_ref() RPC.
-- ============================================================

create table if not exists bookings (
  id                    uuid primary key default uuid_generate_v4(),
  booking_ref           text unique not null,
  user_id               uuid references auth.users(id),
  guest_name            text,
  guest_email           text,
  guest_phone           text,
  special_requests      text,
  chateau_id            uuid not null references chateaux(id),
  bundle_id             uuid not null references bundles(id),
  visit_date            date not null,
  visit_time            time not null,
  persons               integer not null default 2,
  language              text not null default 'en',
  ai_wine_style         text,
  ai_budget             numeric,
  ai_group_type         text,
  price_per_person      numeric not null,
  total_price           numeric not null,
  tax_amount            numeric not null default 0,
  currency              text not null default 'EUR',
  status                text not null default 'pending'
                          check (status in ('pending','confirmed','cancelled','completed','refunded')),
  stripe_payment_intent text,
  paid_at               timestamptz,
  qr_code               text,
  qr_expires_at         timestamptz,
  cancellation_deadline timestamptz,
  cancelled_at          timestamptz,
  cancel_reason         text,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create index if not exists idx_bookings_chateau on bookings(chateau_id);
create index if not exists idx_bookings_user    on bookings(user_id);
create index if not exists idx_bookings_ref     on bookings(booking_ref);

-- ── Migration: add Phase 2 guest-contact columns ────────────────
-- The live `bookings` table predates this file and is missing these
-- three columns used by /book/[slug]/details. Safe to run repeatedly.
alter table bookings add column if not exists guest_name       text;
alter table bookings add column if not exists guest_phone      text;
alter table bookings add column if not exists special_requests text;

-- ── Confirmation code generator ───────────────────────────────
-- generate_booking_ref(chateau_slug) already exists on this project
-- and returns a unique booking_ref string; no change needed here.

-- ── RLS ─────────────────────────────────────────────────────────
-- All booking reads/writes go through API routes using the service
-- role key (supabaseAdmin), which bypasses RLS. No anon/authenticated
-- policies are defined, so the bookings table is not directly
-- reachable from the browser's anon Supabase client.
alter table bookings enable row level security;
